# Generated by Django 5.1.2 on 2024-10-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataaccess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerdata',
            old_name='Sibsp',
            new_name='SibSp',
        ),
        migrations.AddField(
            model_name='passengerdata',
            name='Parch',
            field=models.IntegerField(default=0),
        ),
    ]
