# Generated by Django 4.2.16 on 2024-10-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customroles',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
        ),
    ]
