# Generated by Django 4.2.16 on 2024-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_customroles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customroles',
            name='can_view_both',
            field=models.BooleanField(default=False),
        ),
    ]
